FROM python:3.11

WORKDIR /app

COPY app_streamlit/requirements.txt .

RUN pip install -r requirements.txt

COPY app_streamlit/ .

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]